In [16]:
import numpy as np
import pandas as pd
from pathlib import Path
import json

In [21]:
current_directory = Path.cwd().parent
discharge_directory = Path.joinpath(current_directory, "Data Start Point")
battery_state_file = Path.joinpath(discharge_directory, "battery_state.csv")

In [22]:
df = pd.read_csv(battery_state_file)
df.tail()

,SoC,OCV,R0,R1,R2,C1,C2,Tau1,Tau2
99996,99.996,52.419195,0.334756,-0.058386,-0.039165,249.471688,-3402.502823,-50.330676,-555.712945
99997,99.997,52.419206,0.334780,-0.058396,-0.039175,249.456954,-3402.910607,-50.338063,-555.786656
99998,99.998,52.419216,0.334804,-0.058405,-0.039186,249.442219,-3403.318399,-50.345450,-555.860373
99999,99.999,52.419227,0.334827,-0.058415,-0.039196,249.427484,-3403.726198,-50.352838,-555.934094
100000,100.000,52.419237,0.334851,-0.058424,-0.039207,249.412749,-3404.134006,-50.360226,-556.007820

In [24]:
if df['SoC'].max() > 1:
    df['SoC'] = df['SoC'] / 100
df.tail()

,SoC,OCV,R0,R1,R2,C1,C2,Tau1,Tau2
99996,0.99996,52.419195,0.334756,-0.058386,-0.039165,249.471688,-3402.502823,-50.330676,-555.712945
99997,0.99997,52.419206,0.334780,-0.058396,-0.039175,249.456954,-3402.910607,-50.338063,-555.786656
99998,0.99998,52.419216,0.334804,-0.058405,-0.039186,249.442219,-3403.318399,-50.345450,-555.860373
99999,0.99999,52.419227,0.334827,-0.058415,-0.039196,249.427484,-3403.726198,-50.352838,-555.934094
100000,1.00000,52.419237,0.334851,-0.058424,-0.039207,249.412749,-3404.134006,-50.360226,-556.007820

In [25]:
df['SoC'] = df['SoC'].round(9)

In [26]:
df.to_csv(battery_state_file, index=False)