In [2]:
import numpy as np
import pandas as pd
from pathlib import Path

In [3]:
current_directory = Path.cwd().parent
discharge_directory = Path.joinpath(current_directory, "Data Start Point")
ocv_soc_dict_file_name = Path.joinpath(discharge_directory, "ocv_soc_dict.csv")
battery_state = Path.joinpath(discharge_directory, "battery_state.csv")

In [7]:
state_df = pd.read_csv(battery_state)
state_df.tail()

,SoC,OCV,R0,R1,R2,C1,C2,Tau1,Tau2
99996,0.99996,57.467359,0.041021,0.012137,0.004938,5650.446792,104141.318380,68.581427,514.284719
99997,0.99997,57.467531,0.041021,0.012137,0.004938,5650.822751,104141.707741,68.582798,514.270515
99998,0.99998,57.467704,0.041022,0.012136,0.004938,5651.198774,104142.096591,68.584170,514.256309
99999,0.99999,57.467876,0.041023,0.012136,0.004938,5651.574861,104142.484932,68.585541,514.242101
100000,1.00000,57.468048,0.041023,0.012135,0.004938,5651.951013,104142.872762,68.586913,514.227891

In [8]:
ocv_soc_dict = pd.read_csv(ocv_soc_dict_file_name)
ocv_soc_dict.tail()

            SoC        OCV
99996    99.996  58.207499
99997    99.997  58.207472
99998    99.998  58.207375
99999    99.999  58.207107
100000  100.000  58.207107

In [9]:
state_df['OCV'] = ocv_soc_dict['OCV']

In [10]:
state_df.tail()

,SoC,OCV,R0,R1,R2,C1,C2,Tau1,Tau2
99996,0.99996,58.207499,0.041021,0.012137,0.004938,5650.446792,104141.318380,68.581427,514.284719
99997,0.99997,58.207472,0.041021,0.012137,0.004938,5650.822751,104141.707741,68.582798,514.270515
99998,0.99998,58.207375,0.041022,0.012136,0.004938,5651.198774,104142.096591,68.584170,514.256309
99999,0.99999,58.207107,0.041023,0.012136,0.004938,5651.574861,104142.484932,68.585541,514.242101
100000,1.00000,58.207107,0.041023,0.012135,0.004938,5651.951013,104142.872762,68.586913,514.227891

In [11]:
state_df.to_csv(battery_state, index=False)